<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @page { margin: 120px 40px 100px 40px; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111827; }
        .header { position: fixed; top: -100px; left: 0; right: 0; height: 90px; }
        .footer { position: fixed; bottom: -80px; left: 0; right: 0; height: 70px; }
        .accent { color: {{ $accentColor ?? '#0d9488' }}; }
        .hr { border-top: 1px solid #e5e7eb; margin: 12px 0; }
    </style>
</head>
<body>
    <div class="header">
        @if(!empty($headerImagePath))
            <img src="{{ $headerImagePath }}" style="width:100%; height:auto;">
        @else
            <div style="font-size: 16px; font-weight: 700;" class="accent">{{ $companyName ?? 'Company' }}</div>
            <div class="hr"></div>
        @endif
    </div>

    <div class="footer">
        @if(!empty($footerImagePath))
            <img src="{{ $footerImagePath }}" style="width:100%; height:auto;">
        @else
            <div class="hr"></div>
            <div style="font-size:10px; color:#6b7280;">Generated by WorkTrack Pro</div>
        @endif
    </div>

    <div>
        <div style="font-size: 14px; font-weight: 700;" class="accent">{{ $subject }}</div>
        <div class="hr"></div>
        {!! $body !!}
    </div>
</body>
</html>

